### ISSUE TITLE
bug in all conditional branches

### ISSUE THREAD

**Issue by esaulenka** [desrdev/ghidra-fr60#4]
I am not familiar with FR60's, I just started playing with it.

But I found that @mumbel (hi!) made a mistake in his commit.

All code in `CC:` table should be rewritten from
`CC: "RA" is cc=0x0 { local tmp:1 = 1; export *[const]:1 tmp; }`
to
`CC: "RA" is cc=0x0 { local tmp:1 = 1; export tmp; }`

Current implementation tries to read memory at address 0 or 1, this is completely wrong.

**Comment by mumbel** [comment]
@esaulenka   thanks... i knew it looked off in the deocmpiler, but that didn't click it was off.  added to #3 

merged

**Comment by esaulenka** [comment]
@DiscoStarslayer please close this issue, now it works as expected

**Comment by DiscoStarslayer** [comment]
Fixed in https://github.com/desrdev/ghidra-fr60/pull/3. Thank you @mumbel @esaulenka
